# Generated by Django 5.2.17 on 2026-10-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Weekly Trends', max_length=200)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium_creator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_price',
        ),
        migrations.RemoveField(
            model_name='track',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='track',
            name='price',
        ),
        migrations.AddField(
            model_name='track',
            name='audiomack_url',
            field=models.URLField(blank=True, help_text='Audiomack link for this song.'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('hiphop', 'Hip-Hop'), ('dance', 'Dance'), ('amapiano', 'Amapiano'), ('gospel', 'Gospel'), ('afrobeats', 'Afrobeats'), ('rnb', 'R&B'), ('pop', 'Pop'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Spotify link for this song.'),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube link for this song.'),
        ),
        migrations.CreateModel(
            name='WeeklyTrendSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_trends', to='core.track')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.weeklytrend')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddConstraint(
            model_name='weeklytrendsong',
            constraint=models.UniqueConstraint(fields=('trend', 'track'), name='unique_track_per_trend'),
        ),
        migrations.AddConstraint(
            model_name='weeklytrendsong',
            constraint=models.UniqueConstraint(fields=('trend', 'rank'), name='unique_rank_per_trend'),
        ),
    ]
